"""In-app lessons and primary references for the Cros learning center."""

from __future__ import annotations

from app_catalog import CATALOG, TOOL_KEYS


SOURCES = [
    {"id": "blackbird", "name": "Blackbird", "kind": "DATA SOURCE", "topic": "Identity", "url": "https://github.com/p1ngul1n0/blackbird", "description": "Open-source username enumeration engine used by the optional account-search workflow."},
    {"id": "google-search", "name": "Google Search guidance", "kind": "DOCUMENTATION", "topic": "Search", "url": "https://www.google.com/search/howsearchworks/", "description": "Background on how public web search works and how results are selected."},
    {"id": "hibp", "name": "Have I Been Pwned", "kind": "DATA SOURCE", "topic": "Identity", "url": "https://haveibeenpwned.com/", "description": "Defensive breach-notification service for checking your own email addresses and domains."},
    {"id": "wayback", "name": "Internet Archive Wayback Machine", "kind": "DATA SOURCE", "topic": "Web", "url": "https://web.archive.org/", "description": "Public archive for reviewing historical versions of websites."},
    {"id": "crtsh", "name": "crt.sh Certificate Search", "kind": "DATA SOURCE", "topic": "Domains", "url": "https://crt.sh/", "description": "Certificate Transparency search useful for public certificate and subdomain research."},
    {"id": "iana-rdap", "name": "IANA RDAP requirements", "kind": "STANDARD", "topic": "Domains", "url": "https://www.iana.org/help/rdap-requirements", "description": "Authoritative background for modern public domain-registration lookups."},
    {"id": "owasp-headers", "name": "OWASP HTTP Headers Cheat Sheet", "kind": "REFERENCE", "topic": "Web Defense", "url": "https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html", "description": "Defensive explanations and recommendations for common HTTP security headers."},
    {"id": "nist-hash", "name": "NIST Secure Hash Standard", "kind": "STANDARD", "topic": "Files", "url": "https://www.nist.gov/publications/secure-hash-standard", "description": "Primary reference for SHA-family cryptographic hash functions."},
    {"id": "google-lens", "name": "Google Lens", "kind": "DATA SOURCE", "topic": "Images", "url": "https://lens.google.com/", "description": "Visual-search service for finding similar images, objects, text, and possible locations."},
    {"id": "tineye", "name": "TinEye", "kind": "DATA SOURCE", "topic": "Images", "url": "https://tineye.com/", "description": "Reverse-image search service useful for locating earlier or alternate copies of an image."},
    {"id": "openstreetmap", "name": "OpenStreetMap", "kind": "DATA SOURCE", "topic": "Location", "url": "https://www.openstreetmap.org/", "description": "Open geographic reference for validating coordinates and visible map features."},
    {"id": "virustotal", "name": "VirusTotal", "kind": "DATA SOURCE", "topic": "File Defense", "url": "https://www.virustotal.com/", "description": "Reputation research service. Never upload private, confidential, or sensitive files."},
    {"id": "ms-defender", "name": "Microsoft Defender PowerShell reference", "kind": "DOCUMENTATION", "topic": "Windows Defense", "url": "https://learn.microsoft.com/en-us/defender-endpoint/use-powershell-cmdlets-microsoft-defender-antivirus", "description": "Official Microsoft documentation for Defender status, scans, preferences, and updates."},
    {"id": "ms-scan", "name": "Microsoft Start-MpScan", "kind": "DOCUMENTATION", "topic": "Windows Defense", "url": "https://learn.microsoft.com/en-us/powershell/module/defender/start-mpscan?view=windowsserver2022-ps", "description": "Official reference for starting Microsoft Defender scans."},
    {"id": "ms-audit", "name": "Microsoft advanced audit policy", "kind": "DOCUMENTATION", "topic": "Windows Events", "url": "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/advanced-audit-policy-configuration", "description": "Official guidance for Windows security auditing and logon event coverage."},
    {"id": "ms-bitlocker", "name": "Microsoft BitLocker FAQ", "kind": "DOCUMENTATION", "topic": "Device Protection", "url": "https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/faq", "description": "Official reference for Windows drive encryption and protection behavior."},
    {"id": "mitre-attack", "name": "MITRE ATT&CK", "kind": "REFERENCE", "topic": "Threat Behavior", "url": "https://attack.mitre.org/", "description": "Public knowledge base for describing adversary behaviors and defensive observations."},
    {"id": "sysinternals", "name": "Microsoft Sysinternals", "kind": "TOOLKIT", "topic": "Windows Defense", "url": "https://learn.microsoft.com/en-us/sysinternals/", "description": "Official Microsoft utilities for deeper process, startup, file, and network inspection."},
    {"id": "nord-windows-cli", "name": "NordVPN Windows command-line controls", "kind": "DOCUMENTATION", "topic": "VPN", "url": "https://support.nordvpn.com/hc/en-us/articles/19919384880145-Connect-to-NordVPN-Windows-with-Command-Prompt", "description": "Official connect, country/group selection, and disconnect commands used by the Cros VPN panel."},
    {"id": "nord-no-logs", "name": "NordVPN no-log policy", "kind": "PRIVACY POLICY", "topic": "VPN", "url": "https://nordvpn.com/features/no-log-vpn/", "description": "NordVPN's current description of its no-log policy and independent verification history."},
    {"id": "iana-media-types", "name": "IANA Media Types", "kind": "STANDARD", "topic": "Files", "url": "https://www.iana.org/assignments/media-types/media-types.xhtml", "description": "Authoritative registry of media types used when comparing a file extension with its likely content type."},
    {"id": "ietf-jwt", "name": "IETF JSON Web Token standard", "kind": "STANDARD", "topic": "Data", "url": "https://www.rfc-editor.org/rfc/rfc7519", "description": "Primary JWT format reference. Decoding claims is separate from validating a token's signature and trust."},
    {"id": "ms-firewall-rules", "name": "Microsoft Get-NetFirewallRule", "kind": "DOCUMENTATION", "topic": "Windows Defense", "url": "https://learn.microsoft.com/en-us/powershell/module/netsecurity/get-netfirewallrule?view=windowsserver2025-ps", "description": "Official Microsoft reference for reading Windows Firewall rule properties and policy sources."},
    {"id": "ms-smartscreen", "name": "Microsoft Defender SmartScreen settings", "kind": "DOCUMENTATION", "topic": "Windows Defense", "url": "https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/available-settings", "description": "Official Microsoft reference for SmartScreen and reputation-based protection settings."},
    {"id": "ms-winre", "name": "Windows Recovery Environment", "kind": "DOCUMENTATION", "topic": "Recovery", "url": "https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-recovery-environment--windows-re--technical-reference?view=windows-11", "description": "Official Microsoft technical reference for Windows Recovery Environment and recovery readiness."},
    {"id": "ms-certificates", "name": "PowerShell Certificate provider", "kind": "DOCUMENTATION", "topic": "Certificates", "url": "https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-7.6", "description": "Official Microsoft reference for inspecting Windows certificate stores through PowerShell."},
    {"id": "ms-features", "name": "Microsoft Get-WindowsOptionalFeature", "kind": "DOCUMENTATION", "topic": "Windows Defense", "url": "https://learn.microsoft.com/en-us/powershell/module/dism/get-windowsoptionalfeature?view=windowsserver2025-ps", "description": "Official Microsoft reference for reviewing optional Windows component state."},
    {"id": "ms-credential-guard", "name": "Microsoft Credential Guard", "kind": "DOCUMENTATION", "topic": "Identity Protection", "url": "https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/", "description": "Official Microsoft guidance for virtualization-based credential protection and its operating state."},
    {"id": "ms-powershell-policy", "name": "Microsoft Get-ExecutionPolicy", "kind": "DOCUMENTATION", "topic": "PowerShell", "url": "https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-executionpolicy?view=powershell-7.6", "description": "Official reference for reviewing PowerShell execution policies by scope."},
]


# best use, required input, practical workflow, interpretation, source ids
GUIDE_NOTES = {
    "osint:1": ("Checking whether one exact handle appears on public services.", "An exact username, without an @ symbol.", "Run the search, open only plausible public matches, and compare profile details across more than one source.", "A name match is only a lead; shared usernames do not prove identity.", ["blackbird"]),
    "osint:2": ("Testing likely handle variations when the exact username is unknown.", "Known name fragments, aliases, years, or separators that are already public.", "Generate a small, focused set of combinations, then check the strongest candidates before expanding.", "Repeated profile details matter more than the number of matching handles.", ["blackbird"]),
    "osint:3": ("Finding public pages that mention an email you own or are authorized to research.", "A complete email address.", "Search the exact address first, then review public pages and separate direct mentions from unrelated text.", "Treat scraped directory pages as low-confidence until another source agrees.", ["google-search", "hibp"]),
    "osint:4": ("Checking whether your address appears in known public breach notifications.", "Your own email address or a domain you are authorized to monitor.", "Open the defensive breach resource, submit the approved identifier, and review breach dates and exposed data classes.", "A breach hit means the old credential should be considered exposed; it does not prove current account access.", ["hibp"]),
    "osint:6": ("Comparing a public website across time.", "A public URL or domain plus an approximate date.", "Open the archive, select snapshots around the event, and compare ownership, contact, download, and policy changes.", "Missing snapshots mean no capture was available, not that the page did not exist.", ["wayback"]),
    "osint:7": ("Building precise web searches without memorizing operators.", "A public subject plus one or two facts such as domain, phrase, or file type.", "Start narrow, generate the query, inspect results, and remove one restriction at a time if nothing useful appears.", "Search rank is not evidence quality; preserve the original page and publication date.", ["google-search"]),
    "osint:8": ("Finding public paste-page references connected to an approved term.", "A non-secret username, domain, indicator, or your own email address.", "Search the indicator, avoid downloading unknown attachments, and record only the minimum relevant context.", "Public paste content can be fabricated, outdated, or malicious; corroborate every claim.", ["google-search"]),
    "osint:9": ("Inventorying links exposed by a public web page.", "A full http or https URL.", "Fetch the page, review same-site and external links separately, and investigate only authorized destinations.", "Extracted URLs show what the page references, not whether each destination is safe.", ["owasp-headers"]),
    "osint:5": ("Checking reachable TCP services on a system you own or have permission to test.", "An authorized hostname or IP address and a limited port range.", "Confirm scope, scan a small common-port set first, then validate unexpected listeners locally.", "An open port shows reachability, not a vulnerability; identify the owning service before judging risk.", ["mitre-attack"]),
    "osint:10": ("Adding public network ownership and rough location context to an IP.", "A public IP address.", "Run the lookup, compare network owner, ASN, and country fields, then validate with another public record when important.", "IP geolocation is approximate and may identify a provider or VPN exit rather than a person.", ["iana-rdap"]),
    "osint:11": ("Discovering public hosts associated with a domain you control or may research.", "A registered domain, without a path.", "Collect certificate and DNS candidates, resolve them, and review only hosts within the approved domain scope.", "Certificate names can be historical, shared, or no longer active.", ["crtsh"]),
    "osint:12": ("Reviewing public registration and registrar data for a domain.", "A registered domain name.", "Run the lookup, record registrar, important dates, and public status values, then compare against DNS observations.", "Privacy redaction is normal; public registration data rarely identifies the site operator by itself.", ["iana-rdap"]),
    "osint:13": ("Inspecting how a domain resolves and routes mail.", "A domain name and, if needed, a record type.", "Review A/AAAA, MX, NS, TXT, and CNAME records, then note unexpected providers or stale values.", "DNS is live infrastructure data and can change quickly; record the check time.", ["iana-rdap"]),
    "osint:14": ("Checking certificate identity, issuer, dates, and name coverage.", "A public TLS hostname and optional port.", "Connect to the host, compare subject names with the intended domain, and review issuer and expiry.", "A valid certificate protects the connection; it does not prove the website itself is trustworthy.", ["crtsh"]),
    "osint:15": ("Reading local photo metadata and starting reverse-image or location research.", "A local image you are permitted to inspect.", "Read metadata first, then compare visual landmarks with Lens, TinEye, and maps; keep possible locations labeled as hypotheses.", "Metadata can be missing or edited, and visual matches are clues rather than proof of where a photo was taken.", ["google-lens", "tineye", "openstreetmap"]),
    "osint:16": ("Creating a repeatable fingerprint for text without sending it online.", "The exact text to hash and the desired hash family.", "Select SHA-256 for general comparison, paste the exact text, and save the output with context.", "A matching hash strongly indicates identical input; a hash cannot reveal the original text on its own.", ["nist-hash"]),
    "osint:17": ("Changing the terminal presentation without affecting investigations.", "Your preferred accent, border, title, and wing settings.", "Adjust one visual option at a time, preview it, and save only after the console remains readable.", "Appearance changes do not alter scan logic or collected results.", []),
    "osint:18": ("Understanding what Cros does, what stays local, and its responsible-use boundaries.", "No target input is required.", "Read the scope and privacy notes before using network or third-party workflows.", "Use the access badge on every card to tell whether a workflow is local, networked, browser-based, or elevated.", []),
    "osint:19": ("Checking a public Minecraft name and reviewing the profile record returned by PlayerDB.", "A Minecraft name using 3–16 lowercase letters, numbers, or underscores, or the local generator mode.", "Choose lookup or generate, record only the public profile details you need, and use an availability result only as a lead.", "A public name match does not identify or prove ownership of a person; no email or private account data is collected by NameSniper.", []),

    "advanced:1": ("Reviewing security, privacy, caching, and server response headers.", "A full public http or https URL.", "Fetch the headers, compare missing protections with OWASP guidance, and verify findings in the application context.", "A missing header may be a hardening opportunity, not an exploitable flaw by itself.", ["owasp-headers"]),
    "advanced:2": ("Getting a fast, combined view of a domain's DNS, TLS, and website behavior.", "A domain you are authorized to inspect.", "Run the overview, review each evidence group separately, then use focused tools on anything unexpected.", "The overview is triage; confirm important findings with the dedicated DNS, TLS, or header tool.", ["iana-rdap", "crtsh", "owasp-headers"]),
    "advanced:3": ("Checking what a site intentionally exposes through robots.txt and sitemap files.", "A public site origin such as https://example.com.", "Retrieve both files, review listed paths, and treat disallowed locations as boundaries rather than invitations.", "A listed path is not proof of sensitive content or permission to access it.", ["google-search"]),
    "advanced:4": ("Breaking a suspicious or complex URL into readable parts without opening it.", "The complete URL as text.", "Paste the URL, inspect scheme, hostname, port, path, and decoded query values, then compare the real host with the claimed brand.", "Look-alike domains, raw IP hosts, unusual ports, and nested redirect parameters deserve review.", ["google-search"]),
    "advanced:5": ("Understanding where a public link redirects before trusting the final page.", "A public URL that is safe and authorized to request.", "Trace the chain, inspect every hostname and status code, and stop if a hop leaves the expected scope.", "Redirects are common; unexpected domain changes or repeated loops are the useful signals.", ["owasp-headers"]),
    "advanced:6": ("Collecting public page title, canonical URL, description, and sharing metadata.", "A public page URL.", "Fetch the page, compare declared canonical and social URLs with the requested host, and record discrepancies.", "Metadata is controlled by the page owner and may be inaccurate or intentionally misleading.", ["google-search"]),
    "advanced:7": ("Reviewing an email's transport route and authentication clues.", "Raw message headers from an email you are allowed to inspect.", "Paste headers only, review Received lines from bottom to top, and compare SPF, DKIM, DMARC, Message-ID, and return path.", "A pass result helps verify a sending domain but does not guarantee the message content is safe.", ["google-search"]),
    "advanced:8": ("Creating multiple local fingerprints for a file.", "A local file you are permitted to read.", "Choose the file, calculate checksums, and use SHA-256 as the main comparison value while retaining legacy hashes only for compatibility.", "A changed hash means the bytes changed; it does not explain whether the change was malicious.", ["nist-hash"]),
    "advanced:9": ("Generating a strong password or estimating the structure of a password locally.", "A desired length, or a password you can safely evaluate on this device.", "Prefer a generated unique password, store it in a password manager, and never reuse it across accounts.", "Strength estimates are approximate; uniqueness and length matter more than decorative substitutions.", ["nist-hash"]),
    "advanced:10": ("Checking whether a public IP currently has a reverse hostname.", "A public IP address.", "Run the reverse lookup, record the returned hostname, and validate forward resolution if identity matters.", "Reverse DNS is set by the address owner and is not proof that a service belongs to the named organization.", ["iana-rdap"]),
    "advanced:11": ("Understanding the size and boundaries of an IPv4 or IPv6 network.", "An address with CIDR prefix, such as 192.0.2.10/24.", "Enter the network, review first/last address and host count, and use the result to document approved scope.", "CIDR math describes address ranges; it does not show which hosts are live.", ["iana-rdap"]),
    "advanced:12": ("Encoding data for transport or decoding Base64 text locally.", "Plain text or a Base64 string from a trusted source.", "Choose encode or decode, inspect the local result, and never treat decoded content as automatically safe.", "Base64 is an encoding, not encryption; anyone can reverse it.", ["nist-hash"]),
    "advanced:13": ("Estimating a likely hash family before choosing analysis or comparison tools.", "A hash string copied exactly.", "Paste the value, compare length and character set, then confirm using context from the source system.", "Many formats share the same shape, so the result is a shortlist rather than a guarantee.", ["nist-hash"]),
    "advanced:14": ("Converting event timestamps into readable local and UTC times.", "A Unix timestamp or a readable date and timezone.", "Select the direction, convert it, and record both UTC and local time in case notes.", "Always keep timezone context; the same clock time can represent different moments.", []),
    "advanced:15": ("Validating and formatting JSON without uploading it.", "JSON text that is safe to view locally.", "Paste the data, format it, and use the first reported syntax position to repair invalid input.", "Valid JSON only confirms structure, not that field values are true or safe.", []),
    "advanced:16": ("Validating coordinates and preparing a map comparison.", "Latitude and longitude in decimal degrees.", "Enter the pair, confirm hemisphere and valid ranges, then compare the location across map and imagery sources.", "Coordinates can be rounded, copied incorrectly, or intentionally altered.", ["openstreetmap"]),
    "advanced:17": ("Keeping a timestamped local investigation log.", "A case name and a short factual note with source context.", "Create or select a case, add observations as they occur, and distinguish facts, assumptions, and next steps.", "Good notes preserve source, time, and confidence so another person can reproduce the work.", []),
    "advanced:18": ("Preparing the optional Blackbird account-search engine.", "A working Python environment and permission to install the optional engine dependencies.", "Run diagnostics, complete setup, then test one harmless username before relying on the integration.", "Engine coverage and website behavior change; failed checks are not proof an account is absent.", ["blackbird"]),
    "advanced:19": ("Finding missing local packages, folders, permissions, or connectivity before a workflow.", "No investigation target is needed.", "Run diagnostics, fix only the reported prerequisite, then repeat the check before launching the affected tool.", "A passed diagnostic confirms prerequisites, not the accuracy of third-party data.", []),
    "advanced:20": ("Learning the complete OSINT workflow without leaving the app.", "Choose a tool or investigation path from the Learning Center.", "Use the lesson list, follow the safe steps, open related tools, and mark lessons complete as you learn them.", "The lessons teach repeatable research; they do not replace authorization or source verification.", ["google-search"]),
    "advanced:21": ("Checking whether a file's extension agrees with its actual header before opening it.", "A local file you are permitted to inspect.", "Select the file, compare the extension and MIME guess with the detected header signature, and follow up with checksums or a static scan if they disagree.", "A mismatch can come from harmless renaming or an unusual format; it is a review signal, not proof of malware.", ["iana-media-types"]),
    "advanced:22": ("Turning a mixed indicator list into a clean, deduplicated case list.", "IPs, domains, URLs, or hash values pasted as text or supplied in a local text file.", "Normalize the input locally, review each classification, and save only approved indicators with the case context that produced them.", "Classification is structural; it does not determine whether an indicator is malicious, current, or correctly attributed.", ["iana-rdap"]),
    "advanced:23": ("Reviewing exact line changes between two logs, exports, or configuration snapshots.", "Two local text files that are safe to read on this device.", "Choose the older file first and newer file second, generate the unified comparison, then distinguish expected edits from unexplained additions or removals.", "A difference report shows changed text only; it cannot explain who made the change or whether it was harmful.", []),
    "advanced:24": ("Reading the non-secret header and claim payload of a JWT without uploading it.", "A JWT string from a system you own or are authorized to troubleshoot.", "Paste the token locally, inspect issuer, audience, subject, and time claims, then validate its signature in the issuing application before trusting any claim.", "Successful decoding does not validate the signature, issuer, audience, expiry, or authorization.", ["ietf-jwt"]),

    "security:1": ("Triaging possible remote-access malware by correlating multiple Windows signals.", "The local Windows computer; administrator rights improve visibility but are not required to start.", "Run the scan, review processes, external connections, and startup entries together, then verify suspicious files with Defender and signatures.", "One odd process is not proof of a RAT; prioritize several independent signals that point to the same item.", ["ms-defender", "mitre-attack", "sysinternals"]),
    "security:2": ("Reviewing running programs, executable locations, and basic risk clues.", "The local Windows computer.", "Run the audit, sort unusual or unsigned paths first, and verify the publisher and parent process before acting.", "Unknown does not mean malicious; Windows and vendor software often use uncommon names.", ["sysinternals", "mitre-attack"]),
    "security:3": ("Mapping active and listening TCP connections to owning processes.", "The local Windows computer and an active network connection.", "Capture the snapshot, identify the owning PID, and compare unexpected remote addresses with the process path and purpose.", "Established connections can be normal cloud traffic; process ownership and timing provide context.", ["sysinternals", "mitre-attack"]),
    "security:4": ("Checking common registry locations used to start programs at sign-in.", "The local Windows computer.", "Review Run and RunOnce entries, verify each path and publisher, and investigate missing or user-writable targets.", "An autorun is persistence, not automatically malware; confirm its source before removal.", ["sysinternals", "mitre-attack"]),
    "security:5": ("Reviewing enabled scheduled tasks for unexpected commands or persistence.", "Administrator access for complete task visibility.", "Run elevated, inspect task author, trigger, command, and path, then compare questionable items with installed software.", "Microsoft and vendor tasks are common; suspicious location plus unclear ownership is stronger than name alone.", ["mitre-attack", "sysinternals"]),
    "security:6": ("Inspecting running Windows services and their executable paths.", "The local Windows computer.", "Review non-Microsoft services, paths in user-writable folders, and missing binaries, then confirm publisher and installation source.", "A service has powerful persistence, but most third-party services are legitimate.", ["sysinternals", "mitre-attack"]),
    "security:7": ("Checking whether Microsoft Defender is active, current, and reporting normally.", "A Windows computer with Microsoft Defender available.", "Run the status check, review protection switches, signature age, engine version, and recent scan times.", "Disabled protection or stale signatures needs attention; another managed antivirus can explain some disabled fields.", ["ms-defender"]),
    "security:8": ("Starting a standard Microsoft Defender quick scan after confirmation.", "Microsoft Defender enabled and permission to start a local scan.", "Close important work, confirm the action, let the scan complete, and review Defender detections afterward.", "No detection lowers concern but cannot prove the computer is clean.", ["ms-scan", "ms-defender"]),
    "security:9": ("Examining a file locally before opening or uploading it.", "A local file you are permitted to inspect.", "Select the file, review hash, signature, entropy, header, and limited strings, then compare findings with its expected type and source.", "Static clues identify inconsistencies; they do not safely execute or fully classify the file.", ["nist-hash", "virustotal", "mitre-attack"]),
    "security:10": ("Asking Microsoft Defender to scan one selected file or folder.", "A local path and permission to start a Defender custom scan.", "Choose the smallest relevant path, confirm the scan, wait for completion, and review protection history.", "A clean result is one signal; keep source, signature, behavior, and hash context.", ["ms-scan", "ms-defender"]),
    "security:11": ("Researching a file hash without automatically uploading the file.", "A local file or an existing SHA-256 value.", "Calculate SHA-256 locally, search the hash, and upload only if the file is non-sensitive and you explicitly choose to.", "No reputation result often means unknown, not safe; detections require vendor and context review.", ["virustotal", "nist-hash"]),
    "security:12": ("Recording known-good hashes so later changes can be detected.", "A trusted local folder in a known-good state.", "Choose a stable folder, create the baseline, label its date and purpose, and protect the baseline file from casual editing.", "The baseline records bytes at one moment; create it only when you trust the starting state.", ["nist-hash"]),
    "security:13": ("Finding files added, changed, or removed since a trusted baseline.", "A folder and its matching Cros integrity baseline.", "Run the comparison, inspect added and modified files first, and explain expected updates in case notes.", "A difference means change, not compromise; software updates commonly modify files.", ["nist-hash"]),
    "security:14": ("Locating possible exposed API keys or tokens without displaying their values.", "A local code or document folder you are authorized to scan.", "Scan the narrowest folder, review file paths and pattern types, then rotate confirmed secrets before removing them from history.", "Pattern matches include false positives; never paste discovered secrets into search engines or chats.", ["mitre-attack"]),
    "security:15": ("Checking Office files for macros and embedded active content before opening them.", "A local Office document you are permitted to inspect.", "Select the file, review macro and embedded-object indicators, and open risky documents only in a protected analysis environment.", "Macro presence is a risk factor, not proof of malicious behavior.", ["mitre-attack"]),
    "security:16": ("Triaging newly downloaded files with active formats or misleading names.", "The current user's Downloads folder.", "Run the scan, review recent executables, scripts, macro documents, and double extensions, then verify source and signatures.", "File extension and age are triage signals; do not delete solely from this list.", ["ms-defender", "mitre-attack"]),
    "security:17": ("Confirming Windows Firewall coverage across network profiles.", "The local Windows computer.", "Review Domain, Private, and Public profiles, then verify inbound defaults and any profile currently disabled.", "A firewall enabled status is necessary but does not guarantee every rule is safe.", ["ms-defender"]),
    "security:18": ("Finding local hostname overrides that can redirect traffic.", "The local Windows computer.", "Review active hosts-file lines, compare each mapping with its purpose, and investigate unexpected security or update-domain overrides.", "Custom development entries can be normal; unexplained redirects deserve review.", ["mitre-attack"]),
    "security:19": ("Seeing devices recently observed on the local network segment.", "Connection to the local network.", "Run the inventory, compare IP and MAC entries with known devices, and repeat after contacting a device if needed.", "ARP is a recent local cache, not a complete network scan or identity proof.", ["mitre-attack"]),
    "security:20": ("Reviewing domain names recently cached by Windows.", "The local Windows computer.", "Capture the cache, group unusual names, and correlate them with browser history or owning processes where authorized.", "A cached name may come from background software and does not prove a user visited it.", ["mitre-attack"]),
    "security:21": ("Auditing local user accounts, enabled state, and password properties.", "The local Windows computer; elevation may reveal more detail.", "Review enabled administrators, unfamiliar accounts, password settings, and last-use context, then confirm with the device owner.", "Built-in and service-managed accounts can be normal; focus on unexpected enabled access.", ["ms-audit"]),
    "security:22": ("Reviewing recent Defender detections and configuration events.", "A Windows computer with Defender event logs.", "Run the event review, sort by time and severity, and connect each event to the affected file, action, and current status.", "A remediated event still deserves context, while configuration events are not always detections.", ["ms-defender"]),
    "security:23": ("Saving a repeatable local snapshot of protection and activity signals.", "The local Windows computer and a case or support purpose.", "Create the report, note why and when it was captured, then store it with appropriate access controls.", "Reports are point-in-time observations and can contain sensitive device details.", ["ms-defender", "ms-audit"]),
    "security:24": ("Learning every defensive workflow from inside Cros.", "Choose a defensive lesson in the Learning Center.", "Follow the lesson, launch the tool when ready, compare results with the official source, and mark the lesson complete.", "Lessons support safe triage and do not claim malware certainty from a single heuristic.", ["ms-defender", "mitre-attack"]),
    "security:25": ("Getting a high-level view of major Windows protection controls.", "The local Windows computer.", "Run posture, review every REVIEW or UNKNOWN line, and open the focused tool before changing a setting.", "The score is triage, not a security guarantee; managed or unsupported features can appear unknown.", ["ms-defender", "ms-bitlocker"]),
    "security:26": ("Checking update-service health and recent Windows installation history.", "The local Windows computer.", "Review service state, recent successful updates, and pending restart clues, then use Windows Update for remediation.", "Recent history can be incomplete; organization-managed update schedules may differ.", ["ms-defender"]),
    "security:27": ("Confirming firmware trust features and TPM readiness.", "Administrator access and compatible hardware.", "Run elevated, review Secure Boot state, TPM presence, readiness, and version, then compare with device requirements.", "Unsupported and disabled are different; legacy hardware may not provide these features.", ["ms-bitlocker"]),
    "security:28": ("Reviewing drive-encryption coverage without exposing recovery keys.", "Administrator access on a Windows device with BitLocker support.", "Run elevated, review each drive's protection and encryption state, and resolve suspended or unprotected drives through Windows settings.", "Encryption percentage and protection status both matter; Cros never requests recovery keys.", ["ms-bitlocker"]),
    "security:29": ("Auditing remote-management features that can increase attack surface.", "The local Windows computer.", "Review RDP, Remote Assistance, WinRM, remote registry, and SMB settings, then confirm each enabled feature has an owner and need.", "Enabled remote access may be legitimate; unnecessary exposure is the concern.", ["mitre-attack", "ms-audit"]),
    "security:30": ("Finding folders, processes, extensions, or IPs excluded from Defender scanning.", "Administrator access and Microsoft Defender enabled.", "Run elevated, review every exclusion, and verify it against trusted software or policy before changing anything.", "Attackers may add exclusions, but developers and managed applications also use them.", ["ms-defender"]),
    "security:31": ("Inventorying installed browser extensions across common browsers.", "Access to the current user's browser profile folders.", "Review extension name, ID, version, and browser, then remove only through the browser after verifying unexpected entries.", "An unfamiliar ID is not malicious; confirm its store page, permissions, and install source.", ["mitre-attack"]),
    "security:32": ("Reviewing recent active files in temporary folders for triage.", "The current user's local temporary folders.", "Run the scan, prioritize recent executables and scripts, and correlate them with installers, processes, and signatures.", "Temporary files are normal; location plus active type plus unexplained execution is more meaningful.", ["ms-defender", "mitre-attack"]),
    "security:33": ("Checking saved Wi-Fi profiles for modern authentication without revealing passwords.", "Administrator access for complete profile visibility.", "Run elevated, review authentication and cipher types, and update profiles using open or obsolete security.", "Profile security does not measure router patching, signal integrity, or who controls the network.", ["mitre-attack"]),
    "security:34": ("Finding user or system proxy settings that can redirect web traffic.", "The local Windows computer.", "Review user and WinHTTP proxies, compare them with organization or VPN expectations, and investigate unexpected hosts.", "A proxy is often legitimate; unexplained changes or credential-bearing URLs are the warning signs.", ["mitre-attack"]),
    "security:35": ("Auditing programs launched from current-user and all-users Startup folders.", "The local Windows computer.", "Review shortcuts and files, resolve their real targets, and verify publisher and installation source.", "Startup items are common convenience features; user-writable unknown targets deserve priority.", ["sysinternals", "mitre-attack"]),
    "security:36": ("Reviewing recent failed Windows sign-ins for unusual patterns.", "Administrator access and Security log auditing enabled.", "Run elevated, group failures by account, source, time, and logon type, then compare with expected user activity.", "Typos create normal failures; repeated attempts from an unexpected source are more important.", ["ms-audit"]),
    "security:37": ("Focusing on non-loopback listening ports and the processes exposing them.", "The local Windows computer.", "Run the exposure view, identify owning processes, and verify whether each listener is needed and firewalled.", "Listening locally is not always reachable from the internet; profile and router boundaries matter.", ["sysinternals", "mitre-attack"]),
    "security:38": ("Inventorying folders exposed through Windows file sharing.", "Administrator access for complete share visibility.", "Run elevated, separate administrative defaults from custom shares, and verify path, purpose, and permissions for each custom share.", "A share name alone does not show who can access it; review permissions separately when needed.", ["ms-audit"]),
    "security:39": ("Checking whether essential Windows security and management services are running.", "The local Windows computer.", "Review Defender, firewall, event log, WMI, and update service states, then investigate unexpected stops through Windows management tools.", "Some services start on demand; use configured start type and recent events for context.", ["ms-defender", "ms-audit"]),
    "security:40": ("Creating an inventory of installed applications, versions, dates, and publishers.", "The local Windows computer.", "Run the inventory, sort unknown or outdated software, and verify uninstall or update decisions with the device owner.", "Registry inventory can omit portable apps and can contain stale entries.", ["mitre-attack"]),
    "security:41": ("Finding broad enabled inbound allow rules that may expose a Windows service or program.", "Administrator access for complete Windows Firewall rule visibility.", "Run elevated, review enabled inbound allow rules by profile, program, service, protocol, port, and policy source, then verify whether each rule still has a legitimate owner.", "An allow rule does not prove the port is listening or internet-reachable; active profile and network boundaries still matter.", ["ms-firewall-rules"]),
    "security:42": ("Checking whether active Windows adapters are classified as Public, Private, or Domain networks.", "The local Windows computer.", "Review active profiles, adapter names, IPv4 and IPv6 connectivity, and category; use Public for untrusted networks unless a managed policy requires otherwise.", "A profile category controls policy selection but does not prove the network itself is trustworthy.", ["ms-firewall-rules"]),
    "security:43": ("Reviewing UAC elevation behavior and SmartScreen reputation-protection policy signals.", "The local Windows computer.", "Run the audit, investigate disabled or permissive values, and use Windows Security or managed policy to make approved changes.", "Registry policy state can be managed, unsupported, or overridden; unknown values need confirmation in Windows Security.", ["ms-smartscreen"]),
    "security:44": ("Confirming that Windows recovery tooling and restore-point signals are available before an incident.", "Administrator access for the most complete recovery and restore-point view.", "Check Windows RE status and location, review recent restore points, and make sure recovery media and important backups are handled separately.", "Windows RE and restore points assist recovery but are not substitutes for tested backups.", ["ms-winre"]),
    "security:45": ("Finding PATH entries that are missing, duplicated, relative, or writable by a standard user.", "The local Windows computer and permission to inspect environment paths.", "Review each flagged entry, confirm which application added it, and fix ordering or permissions through the owning installer or system settings.", "A writable PATH directory increases search-order risk but does not prove code has been planted there.", ["mitre-attack"]),
    "security:46": ("Finding expired or soon-to-expire certificates in the current user and local computer personal stores.", "Access to the local Windows certificate stores.", "Review subject, issuer, thumbprint, store, and remaining days, then renew or remove only after identifying the application that uses the certificate.", "An expired certificate may be unused; removal without ownership context can break authentication or encryption.", ["ms-certificates"]),
    "security:47": ("Checking whether important Windows event logs exist, are enabled, have useful capacity, and contain recent activity.", "Administrator access for complete event-log metadata.", "Review Security, System, Application, PowerShell, and Defender logs, then investigate disabled, tiny, full, or unexpectedly inactive channels.", "A quiet log can reflect normal inactivity, missing auditing, collection failure, or deliberate clearing; correlate before deciding.", ["ms-audit"]),
    "security:48": ("Reviewing optional Windows components that can add legacy protocol or remote-service exposure.", "Administrator access to read Windows optional feature state.", "Inspect the targeted legacy and high-exposure feature list, confirm business need for enabled entries, and change features only through approved Windows management.", "An enabled feature is an attack-surface signal, not a vulnerability by itself.", ["ms-features"]),
    "security:49": ("Checking whether virtualization-based security and Credential Guard are configured and running.", "Administrator access and compatible Windows hardware for complete state.", "Review configured and running VBS services, compare with device or organization requirements, and verify unsupported results against the Windows edition and firmware capabilities.", "Configured, running, and supported are different states; absence can be expected on some editions or hardware.", ["ms-credential-guard"]),
    "security:50": ("Reviewing effective PowerShell execution policy and defensive script or module logging settings.", "The local Windows computer.", "Compare execution policy by scope, inspect script-block, module, and transcription policy state, and confirm expected enterprise management before changing anything.", "Execution policy is a safety feature rather than a security boundary; logging improves evidence but does not block malicious scripts.", ["ms-powershell-policy", "ms-audit"]),
}


def _requirements(item: dict) -> list[str]:
    access = item["access"]
    values = {
        "local": ["Windows workstation", "No internet required for the main check"],
        "network": ["Internet or network connection", "Authorized public or owned target"],
        "browser": ["Internet connection", "Web browser for the external research source"],
        "admin": ["Run Cros as Administrator", "Permission to inspect this Windows device"],
        "confirm": ["Microsoft Defender available", "Explicit confirmation before the scan starts"],
    }[access]
    return values + ["Permission to inspect the selected data or system"]


def _safety(item: dict) -> str:
    if item["category"] == "security":
        return "Start with observation. Verify the file, account, service, or setting before changing or removing anything."
    if item["access"] in {"network", "browser"}:
        return "Use public information and approved targets only. Do not sign in as another person, bypass access controls, or upload private data."
    return "Keep sensitive input local, preserve context, and treat a single result as a lead until it is independently verified."


def _related(item: dict) -> list[str]:
    peers = [row["key"] for row in CATALOG if row["section"] == item["section"] and row["key"] != item["key"]]
    if len(peers) < 3:
        peers += [row["key"] for row in CATALOG if row["category"] == item["category"] and row["key"] != item["key"] and row["key"] not in peers]
    return peers[:3]


def _build_learning() -> dict[str, dict]:
    if set(GUIDE_NOTES) != TOOL_KEYS:
        missing = sorted(TOOL_KEYS - set(GUIDE_NOTES))
        extra = sorted(set(GUIDE_NOTES) - TOOL_KEYS)
        raise RuntimeError(f"Learning catalog mismatch. Missing={missing}; extra={extra}")
    source_keys = {source["id"] for source in SOURCES}
    unknown_sources = sorted({source_id for note in GUIDE_NOTES.values() for source_id in note[4]} - source_keys)
    if unknown_sources:
        raise RuntimeError(f"Unknown learning sources: {unknown_sources}")

    learning = {}
    for item in CATALOG:
        best_for, required_input, workflow, interpretation, source_ids = GUIDE_NOTES[item["key"]]
        learning[item["key"]] = {
            "key": item["key"],
            "title": item["name"],
            "category": item["category"],
            "section": item["section"],
            "access": item["access"],
            "purpose": item["description"],
            "best_for": best_for,
            "input": required_input,
            "requirements": _requirements(item),
            "steps": [
                f"Open {item['name']} from the Tool Index or this lesson's Launch button.",
                required_input,
                workflow,
                "Record the source, check time, and confidence before using the result in a decision.",
            ],
            "interpretation": interpretation,
            "safety": _safety(item),
            "source_ids": source_ids,
            "related": _related(item),
        }
    return learning


LEARNING = _build_learning()
